server:
   port: 5555
zuul:
   routes:
      users:
         #默认会创建 /hello-service/**
         path: /users/**
         #url: http://localhost:8080/
         serviceId: hello-service
   AccessFilter:
      pre:
         disable: false
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1111/eureka