server:
   #java -jar bootsample.jar --server.port=9000
   #java -Dserver.port=9000 -jar bootsample.jar
   port: 8080
   servlet:
     context-path: /basic

spring:
   datasource:
      name: test
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root123456
   jpa:
      database: MYSQL
      show-sql: true
   redis:
      host: 127.0.0.1
      port: 6379
      #sentinel:
         #master: mymaster
         #nodes: 127.0.0.1:16379,127.0.0.1:16380,127.0.0.1:16381
      #database: 0
