spring:
   application:
      name: consumer
   #增强RestTemplate重试能力
   cloud:
      loadbalancer:
         retry:
           enabled: true
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1111/eureka
server:
   port: 9000