server:
   #java -jar xxx.jar --server.port=9000
   #java -Dserver.port=9000 -jar xxx.jar
   port: 8080
   servlet:
     context-path: /md

spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      data-source1:
         url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8
         username: root
         password: root123456
         initial-size: 5
         min-idle: 5
         test-on-borrow: true
      data-source2:
         url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF8
         username: root
         password: root123456
mybatis:
   mapper-locations: classpath:mapping/*.xml
   type-aliases-package: com.example.boot.domain