server:
   port: 8080
   servlet:
     context-path: /basic

spring:
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      cache: false
   datasource:
      name: test
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8
      username: root
      password: root123456
      filters: stat,wall,log4j
   jpa:
      database: MYSQL
      show-sql: true
   redis:
      database: 0
      lettuce:
         pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
      standalone:
         host: 127.0.0.1
         port: 6379
      sentinel:
         master: mymaster
         nodes: 127.0.0.1:16379,127.0.0.1:16380,127.0.0.1:16381
   rocketmq:
      name-server: 59.151.122.234:9876
orm: mybatis
pagehelper:
   helperDialect: mysql
   reasonable: true
   support-methods-arguments: true
   params: count=countSql
