server:
   port: 7001
spring:
   cloud:
      config:
         server:
            git:
               uri: https://gitee.com/autfish/spring-config-server-demo
               search-paths: config-repo
               username: autfish
               password: momo2014